// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmea29nzZHgKwskIUjHrYejRWbEepyGc',
    appId: '1:530757864859:web:7eca53175cb3dae895a53e',
    messagingSenderId: '530757864859',
    projectId: 'ecoloop-a880b',
    authDomain: 'ecoloop-a880b.firebaseapp.com',
    storageBucket: 'ecoloop-a880b.firebasestorage.app',
    measurementId: 'G-MRXQKNFM3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYy3JdOlrhaeq7lLJiiolUj1dCj95rUw',
    appId: '1:530757864859:android:1da2c1103255b3fc95a53e',
    messagingSenderId: '530757864859',
    projectId: 'ecoloop-a880b',
    storageBucket: 'ecoloop-a880b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3x7K8bLTy5mu0qeBuH1Cnp1zwAXOSL1E',
    appId: '1:530757864859:ios:44e47ec440da8cab95a53e',
    messagingSenderId: '530757864859',
    projectId: 'ecoloop-a880b',
    storageBucket: 'ecoloop-a880b.firebasestorage.app',
    iosBundleId: 'com.example.ecoloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3x7K8bLTy5mu0qeBuH1Cnp1zwAXOSL1E',
    appId: '1:530757864859:ios:44e47ec440da8cab95a53e',
    messagingSenderId: '530757864859',
    projectId: 'ecoloop-a880b',
    storageBucket: 'ecoloop-a880b.firebasestorage.app',
    iosBundleId: 'com.example.ecoloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSmea29nzZHgKwskIUjHrYejRWbEepyGc',
    appId: '1:530757864859:web:38315b5b8070afef95a53e',
    messagingSenderId: '530757864859',
    projectId: 'ecoloop-a880b',
    authDomain: 'ecoloop-a880b.firebaseapp.com',
    storageBucket: 'ecoloop-a880b.firebasestorage.app',
    measurementId: 'G-L32TT55STJ',
  );
}
