import 'package:ecoloop/BinLocator.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'SplashScreen.dart';
import 'SignUp.dart';
import 'Homepage.dart';
import 'Login.dart';
import 'Profile.dart';
import 'Learn.dart';

// Define the custom green color used for the sign-up theme
// This ensures the colorScheme: ColorScheme.fromSeed(seedColor: primaryGreen) works
const Color primaryGreen = Color(0xFF558B5C);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Using the more specific title
      title: 'EcoLoop App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // Combining the theme properties
        // Set the primary font to something similar to the design's serif
        fontFamily: 'Roboto',
        // Apply the custom green color scheme
        colorScheme: ColorScheme.fromSeed(seedColor: primaryGreen),
        useMaterial3: false,
        // The primarySwatch is now derived from the colorScheme, but we can keep it for backward compatibility
        primarySwatch: Colors.green,
      ),

      // The app will start with the SplashScreen, and the SplashScreen widget
      // will be responsible for navigating to SignUpPage or HomePage.
      home: const SplashScreen(),

      // Define routes for easy navigation between your main screens
      routes: {
        // Assuming the class name inside SignUp.dart is SignUpPage
        '/signup': (context) => const SignUpPage(),
        '/home': (context) => const HomePage(),
        '/login': (context) => const LoginPage(),
        '/splash': (context) => const SplashScreen(),
        '/bins': (context) => const BinLocatorPage(),
        '/profile': (context) => const ProfilePage(),
        '/learn': (context) => const LearnPage(),
      },
    );
  }
}
